[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "12.13.0"
  YARN_VERSION = "1.22.0"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
